# Server Configuration
server:
  port: ${PORT:9091}
  servlet:
    context-path: /gisa-mod-service-associate

# Spring Configurations
spring:
  application:
    name: gisa-mod-service-associate
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/gisadb
    username: postgres
    password: postgres
    hikari:
      jdbc-url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/gisadb}
      username: ${POSTGRES_USER:postgres}
      password: ${POSTGRES_PASSWORD}
      driver-class-name: org.postgresql.Driver
      pool-name: CAMUNDA-HIKARI-POOL
      idle-timeout: 3000
      minimum-idle: 30
      maximum-pool-size: 10
      connection-timeout: 2000
      connection-test-query: select 1
      transaction-isolation: TRANSACTION_READ_COMMITTED 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
  session:
    store-type: none
  flyway:
    baselineOnMigrate : true 
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/gisadb}
    schemas: gisamodserviceassociatedb
    password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER:postgres}
    locations: classpath:db/migration
  main:
    allow-bean-definition-overriding: true
  

# Eureka Configurations
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      
camunda:
  bpm:
    enabled: true
    admin-user:
      id: demo
      password: demo
      email: ufo@andromeda.com
      first-name: Andromeda
      last-name: Galaxy
    metrics:
      db-reporter-activate: true
    database:
      schema-update: true
    filter:
      create: All
    authorization:
      enabled: true
    history-level: full
    auto-deployment-enabled: true
    default-number-of-retries: 3
    job-execution:
      enabled: true
    webapp:
      application-path: /camundagisa